package com.mustafakoceerr.justrelax.core.ui.theme

import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF88511D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDCC2)
val onPrimaryContainerLight = Color(0xFF6C3A06)
val secondaryLight = Color(0xFF88511E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDCC3)
val onSecondaryContainerLight = Color(0xFF6C3A06)
val tertiaryLight = Color(0xFF5A631F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDEEA96)
val onTertiaryContainerLight = Color(0xFF424B06)
val errorLight = Color(0xFF904A43)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD5)
val onErrorContainerLight = Color(0xFF73342D)
val backgroundLight = Color(0xFFFFF8F5)
val onBackgroundLight = Color(0xFF221A14)
val surfaceLight = Color(0xFFFFF8F4)
val onSurfaceLight = Color(0xFF211A13)
val surfaceVariantLight = Color(0xFFF2DFD1)
val onSurfaceVariantLight = Color(0xFF51443A)
val outlineLight = Color(0xFF837468)
val outlineVariantLight = Color(0xFFD5C3B5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF372F27)
val inverseOnSurfaceLight = Color(0xFFFDEEE3)
val inversePrimaryLight = Color(0xFFFFB77B)
val surfaceDimLight = Color(0xFFE5D8CC)
val surfaceBrightLight = Color(0xFFFFF8F4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E6)
val surfaceContainerLight = Color(0xFFFAEBE0)
val surfaceContainerHighLight = Color(0xFFF4E6DA)
val surfaceContainerHighestLight = Color(0xFFEEE0D5)

val primaryDark = Color(0xFF80D4D5)
val onPrimaryDark = Color(0xFF003738)
val primaryContainerDark = Color(0xFF004F51)
val onPrimaryContainerDark = Color(0xFF9CF1F2)
val secondaryDark = Color(0xFFFFB877)
val onSecondaryDark = Color(0xFF4B2700)
val secondaryContainerDark = Color(0xFF6B3B03)
val onSecondaryContainerDark = Color(0xFFFFDCC0)
val tertiaryDark = Color(0xFFABD28F)
val onTertiaryDark = Color(0xFF193706)
val tertiaryContainerDark = Color(0xFF2F4F1B)
val onTertiaryContainerDark = Color(0xFFC7EEA9)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF561E19)
val errorContainerDark = Color(0xFF73342D)
val onErrorContainerDark = Color(0xFFFFDAD5)
val backgroundDark = Color(0xFF0E1415)
val onBackgroundDark = Color(0xFFDDE4E3)
val surfaceDark = Color(0xFF15130C)
val onSurfaceDark = Color(0xFFE8E2D4)
val surfaceVariantDark = Color(0xFF4E4539)
val onSurfaceVariantDark = Color(0xFFD2C4B4)
val outlineDark = Color(0xFF9B8F80)
val outlineVariantDark = Color(0xFF4E4539)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE8E2D4)
val inverseOnSurfaceDark = Color(0xFF333027)
val inversePrimaryDark = Color(0xFF00696B)
val surfaceDimDark = Color(0xFF15130C)
val surfaceBrightDark = Color(0xFF3C3930)
val surfaceContainerLowestDark = Color(0xFF100E07)
val surfaceContainerLowDark = Color(0xFF1D1C13)
val surfaceContainerDark = Color(0xFF222017)
val surfaceContainerHighDark = Color(0xFF2C2A21)
val surfaceContainerHighestDark = Color(0xFF37352B)


